# Generated by Django 4.2.1 on 2023-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="stop_loss",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
