# Generated by Django 4.2.1 on 2023-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_trade_stop_loss"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "swap_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
            ],
        ),
    ]
