# Generated by Django 4.2.1 on 2023-05-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading.asset",
            ),
        ),
    ]
