# Generated by Django 4.2.1 on 2023-05-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leverage",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.FloatField(default=5000.0),
        ),
    ]
