# Generated by Django 4.2.1 on 2023-05-11 11:41

from django.db import migrations


import random
import string

def generate_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user_profile in UserProfile.objects.all():
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
            if not UserProfile.objects.filter(referral_code=code).exists():
                user_profile.referral_code = code
                user_profile.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_referral_code"),
    ]

    operations = [
        migrations.RunPython(generate_referral_codes),
    ]
