# Generated by Django 4.2.1 on 2023-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20230511_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
