# Generated by Django 4.2.1 on 2023-06-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userprofile_referrer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=15)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=16)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=16)),
                ("open_time", models.DateTimeField(auto_now_add=True)),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "leverage",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "available_margin",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=16),
                ),
                (
                    "margin_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosedPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=15)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=16)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=16)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=16)),
                ("open_time", models.DateTimeField(auto_now_add=True)),
                ("close_time", models.DateTimeField(auto_now_add=True)),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "profit_or_loss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
