# Generated by Django 4.2.1 on 2023-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_userprofile_margin_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedpositions",
            name="close_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="leverage",
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="open_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="profit_or_loss",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="stop_loss",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="available_margin",
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="equity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="leverage",
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="margin_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="open_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="stop_loss",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
