# Generated by Django 4.2.1 on 2023-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_closedpositions_close_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedpositions",
            name="open_time",
            field=models.DateTimeField(),
        ),
    ]
