# Generated by Django 4.2.1 on 2023-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_closedpositions_open_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpositions",
            name="funding_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="openpositions",
            name="profit_or_loss",
            field=models.FloatField(default=0.0),
        ),
    ]
