# Generated by Django 4.2.1 on 2023-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_openpositions_funding_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpositions",
            name="funding_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
