# Generated by Django 4.2.1 on 2023-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_openpositions_funding_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedpositions",
            name="fund_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
