# Generated by Django 4.2.1 on 2023-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_openpositions_available_margin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpositions",
            name="maintenance_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
