# Generated by Django 4.2.1 on 2023-07-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_battlegame"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closedpositions",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="openpositions",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="leverage",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="closedpositions",
            name="leverage",
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name="openpositions",
            name="leverage",
            field=models.FloatField(default=10.0),
        ),
        migrations.CreateModel(
            name="TradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("balance", models.FloatField(default=5000.0)),
                ("leverage", models.FloatField(default=10.0)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="closedpositions",
            name="trading_profile",
            field=models.ForeignKey(
                default=9999999999,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tradingprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openpositions",
            name="trading_profile",
            field=models.ForeignKey(
                default=999999999,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tradingprofile",
            ),
            preserve_default=False,
        ),
    ]
